---
title: "Title Goes Here"
author: "Ariel C. Zane<br/>More lines here"
date: "March 2, 2018"
output:
  xaringan::moon_reader:
    css: ["default", "new-color.css", "default-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE)
```

# This is the first slide!

--

- You can have elements appear in succession, versus all at once

--

- Like this

--

- And this

--

- This is a [link]("http://tumblr.tastefullyoffensive.com/post/171451780306/squirrel-eats-doughnut#.WpmF52aZOSM") (it me!)

---

# Here we have a table<sup>*</sup>

## and a smaller header

### and a smaller header
```{r}
test_set <-
  mtcars %>%
select(mpg, cyl, disp, hp, drat, wt)

knitr::kable(head(test_set), format = 'html') %>%
kable_styling(full_width = F, font_size = 8)
```
.footnote[
[*]I like a tinier font for footnotes - set this in default-fonts.css
]

---
class: center
# Here we have a table<sup>*</sup>

## and a smaller header

### and a smaller header
```{r}
test_set <-
  mtcars %>%
select(mpg, cyl, disp, hp, drat, wt)

knitr::kable(head(test_set), format = 'html') %>%
kable_styling(full_width = F, font_size = 8)
```
.footnote[
[*]I like a tinier font for footnotes - set this in default-fonts.css
]